### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by CorvusYe** [dudu-ltd/flutter_graph_view#3]
- UI integrity | 关于UI完整性
  - [ ] Edge style | 边风格配置
  - [ ] Vertex description | 节点描述
  - [ ] Legend | 标签图例
  - [ ] Pick list | 选中元素的列表
- Graph structure | 拓展图结构
    - [ ] Virtual vertex used in path scenarios | 用于描述路径场景的虚拟节点
- Event | 事件、交互
    - [ ] Vertex / Edge tap callback  |  节点与边的点击回调
    - [ ] Vertex / Edge hover callback | 节点与边的鼠标浮入回调
    - [ ] Vertex / Edge pick callback | 节点与边选中回调
